### ISSUE TITLE
person tracking and viz

### ISSUE THREAD

**Issue by nd-z** [jz359/orbslam_face#2]
- [ ] face detection/object classification on keyframes ONLY
- [ ] grab bounding box
- [ ] publish to map
